version: '3.8'
services:
  db:
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shopping_item


  app:
    build: .
    image: unicornvecerniskolajavyfinalproject-app:latest
    ports:
      - "3004:3004"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shopping_item
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234